version: '2'
services: 
    application: 
        container_name: forum-api
        build: .
        networks: 
            - forum
        depends_on:
            - neo4j
        env_file: variables.env
        ports:
            - "3000:3000"
    neo4j:
        container_name: neo4j
        image: neo4j:3.1.0        
        networks: 
            - forum
        ports:
            - "7474:7474"
networks: 
    forum:
