version: '2'
services: 
    application: 
        container_name: template-api
        build: .
        networks: 
            - template
        depends_on:
            - mongo
        env_file: variables.env
        ports:
            - "3000:3000"
    mongo:
        container_name: mongo
        image: mongo:latest
        networks: 
            - template
networks: 
    template:
